[behave]
stderr_capture = False
stdout_capture = False
log_capture = False

# Setup logging outputs to console
logging_level = INFO
logging_format = %(asctime)s [%(levelname)s] %(message)s
logging_date_format = %H:%M:%S

# --- ADD THESE LINES TO FIX THE BLANK ALLURE REPORT ---
format = allure_behave.formatter:AllureFormatter
outfiles = reports/allure-results